[tool.poetry]
name = "poc-prorrataerv"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
polars = "^0.20.3"
sqlalchemy-access = "^2.0.2"
duckdb = "^0.9.2"
pyarrow = "^15.0.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.1.11"
jupyter = "^1.0.0"
jupysql = "^0.10.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
