[project]
name = "prorrata"
version = "1.3.3"
description = "Aplicación para la prorrata de centrales de costo variable 0 en el sistema eléctrico chileno (SEN)."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "polars",
    "sqlalchemy-access",
    "pyarrow",
    "xlsx2csv",
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "ipykernel",
    "duckdb"
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
